package pawapaygo

const (
	requestDepositRoute = "/deposits"

	// Countries & Currencies
	CURRENCY_CODE_CAMEROON = "XAF"
	COUNTRY_CODE_CAMEROON  = "CMR"

	CURRENCY_CODE_NIGERIA = "NGN"
	COUNTRY_CODE_NIGERIA  = "NGA"

	CURRENCY_CODE_ZIMBABWE = "ZWL"
	COUNTRY_CODE_ZIMBABWE  = "ZWE"

	CURRENCY_CODE_KENYA = "KES"
	COUNTRY_CODE_KENYA  = "KEN"

	CURRENCY_CODE_BENIN = "XOF"
	COUNTRY_CODE_BENIN  = "BEN"

	CURRENCY_CODE_BURKINAFASO = "XOF"
	COUNTRY_CODE_BURKINAFASO  = "BFA"

	CURRENCY_CODE_COTEDIVOIRE = "XOF"
	COUNTRY_CODE_COTEDIVOIRE  = "CIV"

	CURRENCY_CODE_REPUBLICOFCONGO = "XAF"
	COUNTRY_CODE_REPUBLICOFCONGO  = "COG"

	CURRENCY_CODE_DEMOCRATICREPUBLICOFCONGO_CDF = "CDF"
	CURRENCY_CODE_DEMOCRATICREPUBLICOFCONGO_USD = "USD"
	COUNTRY_CODE_DEMOCRATICREPUBLICOFCONGO      = "COD"

	CURRENCY_CODE_GABON = "XAF"
	COUNTRY_CODE_GABON  = "GAB"

	CURRENCY_CODE_GHANA = "GHS"
	COUNTRY_CODE_GHANA  = "GHA"

	CURRENCY_CODE_MALAWI = "MWK"
	COUNTRY_CODE_MALAWI  = "MWI"

	CURRENCY_CODE_MOZAMBIQUE = "MZN"
	COUNTRY_CODE_MOZAMBIQUE  = "MOZ"

	CURRENCY_CODE_ZAMBIA = "ZMW"
	COUNTRY_CODE_ZAMBIA  = "ZMB"

	CURRENCY_CODE_UGANDA = "UGX"
	COUNTRY_CODE_UGANDA  = "UGA"

	CURRENCY_CODE_TANZANIA = "TZS"
	COUNTRY_CODE_TANZANIA  = "TZA"

	CURRENCY_CODE_SIERRALEONE = "SLE"
	COUNTRY_CODE_SIERRALEONE  = "SLE"

	CURRENCY_CODE_SENEGAL = "XOF"
	COUNTRY_CODE_SENEGAL  = "SEN"

	CURRENCY_CODE_RWANDA = "RWF"
	COUNTRY_CODE_RWANDA  = "RWA"

	// Benin
	MTN_MOMO_BEN = "MTN_MOMO_BEN"
	MOOV_BEN     = "MOOV_BEN"

	// Burkina Faso
	MOOV_BFA   = "MOOV_BFA"
	ORANGE_BFA = "ORANGE_BFA"

	// Cameroon
	MTN_MOMO_CMR = "MTN_MOMO_CMR"
	ORANGE_CMR   = "ORANGE_CMR"

	// Côte d'Ivoire
	MTN_MOMO_CIV = "MTN_MOMO_CIV"
	ORANGE_CIV   = "ORANGE_CIV"

	// Democratic Republic of Congo
	VODACOM_MPESA_COD = "VODACOM_MPESA_COD"
	AIRTEL_COD        = "AIRTEL_COD"
	ORANGE_COD        = "ORANGE_COD"

	// Republic of Congo
	AIRTEL_COG   = "AIRTEL_COG"
	MTN_MOMO_COG = "MTN_MOMO_COG"

	// Gabon
	AIRTEL_GAB = "AIRTEL_GAB"

	// Ghana
	MTN_MOMO_GHA   = "MTN_MOMO_GHA"
	AIRTELTIGO_GHA = "AIRTELTIGO_GHA"
	VODAFONE_GHA   = "VODAFONE_GHA"

	// Kenya
	MPESA_KEN = "MPESA_KEN"

	// Malawi
	AIRTEL_MWI = "AIRTEL_MWI"
	TNM_MWI    = "TNM_MWI"

	// Mozambique
	VODACOM_MOZ = "VODACOM_MOZ"

	// Nigeria
	AIRTEL_NGA   = "AIRTEL_NGA"
	MTN_MOMO_NGA = "MTN_MOMO_NGA"

	// Rwanda
	AIRTEL_RWA   = "AIRTEL_RWA"
	MTN_MOMO_RWA = "MTN_MOMO_RWA"

	// Senegal
	FREE_SEN   = "FREE_SEN"
	ORANGE_SEN = "ORANGE_SEN"

	// Sierra Leone
	ORANGE_SLE = "ORANGE_SLE"

	// Tanzania
	AIRTEL_TZA  = "AIRTEL_TZA"
	VODACOM_TZA = "VODACOM_TZA"
	TIGO_TZA    = "TIGO_TZA"
	HALOTEL_TZA = "HALOTEL_TZA"

	// Uganda
	AIRTEL_OAPI_UGA = "AIRTEL_OAPI_UGA"
	MTN_MOMO_UGA    = "MTN_MOMO_UGA"

	// Zambia
	AIRTEL_OAPI_ZMB = "AIRTEL_OAPI_ZMB"
	MTN_MOMO_ZMB    = "MTN_MOMO_ZMB"
	ZAMTEL_ZMB      = "ZAMTEL_ZMB"
)
